/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualRouteImport } from './routes/visual'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ThumbnailRouteImport } from './routes/thumbnail'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as IndexRouteImport } from './routes/index'

const VisualRoute = VisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ThumbnailRoute = ThumbnailRouteImport.update({
  id: '/thumbnail',
  path: '/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/rating': typeof RatingRoute
  '/research': typeof ResearchRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/thumbnail': typeof ThumbnailRoute
  '/topics': typeof TopicsRoute
  '/visual': typeof VisualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/rating': typeof RatingRoute
  '/research': typeof ResearchRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/thumbnail': typeof ThumbnailRoute
  '/topics': typeof TopicsRoute
  '/visual': typeof VisualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/rating': typeof RatingRoute
  '/research': typeof ResearchRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/thumbnail': typeof ThumbnailRoute
  '/topics': typeof TopicsRoute
  '/visual': typeof VisualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prompts'
    | '/rating'
    | '/research'
    | '/seo'
    | '/settings'
    | '/story'
    | '/thumbnail'
    | '/topics'
    | '/visual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prompts'
    | '/rating'
    | '/research'
    | '/seo'
    | '/settings'
    | '/story'
    | '/thumbnail'
    | '/topics'
    | '/visual'
  id:
    | '__root__'
    | '/'
    | '/prompts'
    | '/rating'
    | '/research'
    | '/seo'
    | '/settings'
    | '/story'
    | '/thumbnail'
    | '/topics'
    | '/visual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptsRoute: typeof PromptsRoute
  RatingRoute: typeof RatingRoute
  ResearchRoute: typeof ResearchRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  StoryRoute: typeof StoryRoute
  ThumbnailRoute: typeof ThumbnailRoute
  TopicsRoute: typeof TopicsRoute
  VisualRoute: typeof VisualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual': {
      id: '/visual'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof VisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thumbnail': {
      id: '/thumbnail'
      path: '/thumbnail'
      fullPath: '/thumbnail'
      preLoaderRoute: typeof ThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptsRoute: PromptsRoute,
  RatingRoute: RatingRoute,
  ResearchRoute: ResearchRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  StoryRoute: StoryRoute,
  ThumbnailRoute: ThumbnailRoute,
  TopicsRoute: TopicsRoute,
  VisualRoute: VisualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
